genesis:
  credit:
    service:
      # change it with dev env url of genesis-credit-service
      baseUrl: http://localhost:8073

server:
  port: 8072
#  servlet:
#    contextPath: /webapp

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # change it with dev env eureka url
      defaultZone: http://localhost:8070/eureka

spring:
#  zipkin:
#    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: genesis-credit-service
          uri: lb://genesis-credit-service
          predicates:
            - Path=/api/credit/**
          filters:
            - RewritePath=/credit/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: actuator-mapping
          uri: lb://gateway-server
          predicates:
            - Path=/actuator/**
          filters:
            - RewritePath=/''/(?<path>.*), /$\{''}

management:
  endpoints:
    web:
      exposure:
        include: "*"

#management:
#  endpoints:
#    enabled-by-default: false
#    web:
#      base-path: /
#      path-mapping.health: health
#  endpoint:
#    health.enabled: true
#    health.show-details: always
  #server.port: 50186