AWSTemplateFormatVersion: "2010-09-09"

Description: |
  ECS Cluster
Parameters:
  VpcId:
    Description: The ID of the existing VPC
    Type: String
  EcsHostSubnets:
    Description: The IDs of the existing subnets
    Type: List<AWS::EC2::Subnet::Id>
  EnvironmentName:
    Type: String
  EnvironmentName1:
    Type: String
  EnvironmentName2:
    Type: String

Resources:

  EfsSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub ${AWS::StackName}-EFSSecurityGroup
      VpcId: !Ref VpcId
      SecurityGroupIngress:  # Allow inbound connections on port 2049 (NFS)
        - IpProtocol: tcp
          FromPort: '2049'
          ToPort: '2049'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging

  EFSFileSystem:
    Type: "AWS::EFS::FileSystem"
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
      FileSystemTags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-efs
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging

  EFSMountTargetA:
    Type: "AWS::EFS::MountTarget"
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Select [ 0, !Ref EcsHostSubnets ]  # add mount target to the first subnet
      SecurityGroups: [!GetAtt EfsSecurityGroup.GroupId]
Outputs:
  EFSFileSystem:
    Description: The ID of the EFS file system
    Value: !Ref EFSFileSystem
    Export:
      Name: EFSFileSystem