AWSTemplateFormatVersion: "2010-09-09"

Description: |
  ECS Cluster

Parameters:
  VpcId:
    Description: The ID of the existing VPC
    Type: AWS::EC2::VPC::Id
  AlbSubnets:
    Description: Create external-facing load balancer in these subnets.
    Type: List<AWS::EC2::Subnet::Id>

  LoadbalancerName:
    Description: load balancer name 
    Type: String
    Default: "network-lb"

  EnvironmentName:
    Type: String
    Default: "prod"

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "network" # Changed to network
      Name: !Ref LoadbalancerName
      Subnets: !Ref AlbSubnets
      Scheme: "internet-facing"

  ECSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: TCP # Changed to TCP
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: TCP # Changed to TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName

  FargateTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: TCP # Changed to TCP
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: TCP # Changed to TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: TCP # Changed to TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSTargetGroup

  ListenerRuleForECSService:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ECSTargetGroup
      Conditions:
        - Field: host-header
          Values: ["pds.example.com"]
      ListenerArn: !Ref LoadBalancerListener
      Priority: 1

  ListenerRuleForFargateService:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref FargateTargetGroup
      Conditions:
        - Field: host-header
          Values: ["pds2.example.com"]
      ListenerArn: !Ref LoadBalancerListener
      Priority: 2

Outputs:
  LoadBalancerListener:
    Description: The ARN of the Load Balancer Listener
    Value: !Ref LoadBalancerListener
    Export:
      Name: LoadBalancerListener
  ECSTargetGroup:
    Description: The ARN of the ECS Target Group
    Value: !Ref ECSTargetGroup
    Export:
      Name: ECSTargetGroup
  FargateTargetGroup:
    Description: The ARN of the Fargate Target Group
    Value: !Ref FargateTargetGroup
    Export:
      Name: FargateTargetGroup
