AWSTemplateFormatVersion: "2010-09-09"

Description: |
  ECS Cluster

Parameters:
Parameters:
  VpcId:
    Description: The ID of the existing VPC
    Type: AWS::EC2::VPC::Id
  AlbSubnets:
    Description: Create external-facing load balancer in these subnets.
    Type: List<AWS::EC2::Subnet::Id>

  LoadbalancerName:
    Description: load balancer name 
    Type: String
    Default: "network-lb"

  EnvironmentName:
    Type: String
    Default: "prod"
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "network"
      Subnets: !Ref AlbSubnets
      Scheme: "internet-facing"
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Ref LoadbalancerName


  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: LoadBalancer
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: TCP
      TargetType: ip  # Change target type to ip
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
Outputs:
  LoadBalancerListener:
    Description: The ARN of the Load Balancer Listener
    Value: !Ref LoadBalancerListener
    Export:
      Name: LoadBalancerListener
  TargetGroup:
    Description: The ARN of the Target Group
    Value: !Ref TargetGroup
    Export:
      Name: TargetGroup