AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Description: The ID of the existing VPC
    Type: AWS::EC2::VPC::Id
  KeyName:
    Description: SSH Keyname for access to ECS Cluster hosts
    Type: AWS::EC2::KeyPair::KeyName
  EcsHostSubnets:
    Description: Create ECS Cluster Hosts in these subnets.
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-nest-stck-code.s3.amazonaws.com/ecs-cluster.yaml
      Parameters:
        VpcId: !Ref VpcId
        ClusterName: "prod-ecs-cluster"
        InstanceType: "t2.nano"
        KeyName: !Ref KeyName
        MinInstanceNo: 1
        MaxInstanceNo: 4
        DesiredInstanceNo: 1
        EcsHostSubnets: !Ref EcsHostSubnets

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-nest-stck-code.s3.amazonaws.com/load-balancer.yaml
      Parameters:
        VpcId: !Ref VpcId
        LoadbalancerName: "network-lb"

  ECSServicesTasksStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-nest-stck-code.s3.amazonaws.com/ecs-services-tasks.yaml
      Parameters:
        VpcId: !Ref VpcId
        FargateServiceName: "fargate-service"

        FargateServiceDesiredCount: 1

        FargateContainerUrl: "nginx:latest"

        FargateTaskDefinitionName: "fargate-nginx-task"

        MyServiceName: "nginx-service"

        NginxServiceDesiredCount: 1

        NginxContainerUrl: "nginx:latest"

        NginxTaskDefinitionName: "nginx-task"

  EFSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-nest-stck-code.s3.amazonaws.com/efs.yaml
      Parameters:
        VpcId: !Ref VpcId
        EnvironmentName: "prod"
        EcsHostSubnets: !Ref EcsHostSubnets
