AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Description: The ID of the existing VPC
    Type: AWS::EC2::VPC::Id
  KeyName:
    Description: SSH Keyname for access to ECS Cluster hosts
    Type: AWS::EC2::KeyPair::KeyName
  EcsHostSubnets:
    Description: Create ECS Cluster Hosts in these subnets.
    Type: List<AWS::EC2::Subnet::Id>
  AlbSubnets:
    Description: Create external-facing load balancer in these subnets.
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://files-navigate.s3.amazonaws.com/ecs-cluster.yaml
      Parameters:
        VpcId: !Ref VpcId
        ClusterName: "prod-ecs-cluster"
        InstanceType: "t2.micro"
        EnvironmentName: "prod"
        EnvironmentName1: "prod"
        EnvironmentName2: "prod"
        KeyName: !Ref KeyName
        MinInstanceNo: 1
        MaxInstanceNo: 4
        DesiredInstanceNo: 1
        EcsHostSubnets: !Join [",", !Ref EcsHostSubnets]

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://files-navigate.s3.amazonaws.com/load-balancer.yaml
      Parameters:
        VpcId: !Ref VpcId
        LoadbalancerName: "application-lb"
        AlbSubnets: !Join [",", !Ref AlbSubnets]

  ECSServicesTasksStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [LoadBalancerStack, EFSStack]
    Properties:
      TemplateURL: https://files-navigate.s3.amazonaws.com/ecs-services-tasks.yaml
      Parameters:
        VpcId: !Ref VpcId
        FargateServiceName: "fargate-service"
        EFSFileSystem: !GetAtt EFSStack.Outputs.EFSFileSystem
        EcsHostSecurityGroup: !GetAtt ECSClusterStack.Outputs.EcsHostSecurityGroup
        FargateServiceDesiredCount: 1
        EnvironmentName: "prod"
        EnvironmentName1: "prod"
        EnvironmentName2: "prod"
        FargateContainerUrl: "nginx:latest"
        FargateTaskDefinitionName: "fargate-nginx-task"
        MyServiceName: "nginx-service"
        NginxServiceDesiredCount: 1
        NginxContainerUrl: "nginx:latest"
        NginxTaskDefinitionName: "nginx-task"
        ECSTargetGroup: !GetAtt LoadBalancerStack.Outputs.ECSTargetGroup
        FargateTargetGroup: !GetAtt LoadBalancerStack.Outputs.FargateTargetGroup
        Cluster: !GetAtt ECSClusterStack.Outputs.Cluster
        EcsHostSubnets: !GetAtt ECSClusterStack.Outputs.EcsHostSubnets
        
  EFSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://files-navigate.s3.amazonaws.com/efs.yaml
      Parameters:
        VpcId: !Ref VpcId
        EnvironmentName: "prod"
        EnvironmentName1: "prod"
        EnvironmentName2: "prod"
        EcsHostSubnets: !Join [",", !Ref EcsHostSubnets]