AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Vpc and subnets

Parameters:
  VpcId:
    Description: Create ECS cluster in this VPC
    Type: AWS::EC2::VPC::Id

  AlbSubnets:
    Description: Create external-facing load balancer in these subnets.
    Type: List<AWS::EC2::Subnet::Id>

  EcsHostSubnets:
    Description: Create ECS Cluster Hosts in these subnets.
    Type: List<AWS::EC2::Subnet::Id>